<?xml version="1.0" encoding="utf-8"?><Database Name="OldsDB" Class="OldsDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=desktop-5e70rm2;Initial Catalog=OldsDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OldsDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.senior" Member="seniors">
    <Type Name="senior">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="birtday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Seniority" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>